### ISSUE TITLE
Changes from testing with Google Chrome Tag Assistant

### ISSUE THREAD

**Issue by tavinus** [quafzi/Inchoo_Adwords#3]
Hi there, I installed this on a Magento CE 1.9.2 and was testing with the Tag Assistant on Chome.

It complains that the Conversion ID should not have quotation marks.

![screen-shot-2016-04-07-at-5 06 40-am](https://cloud.githubusercontent.com/assets/8039413/14344592/f1b33cf2-fc7e-11e5-95ef-c8d1ffbda74a.png)

The main thing is changing the file:
`app/design/frontend/base/default/template/inchoo_adwords/conversion_tracking.phtml`

Line 5, remove quotation marks
From:
`    var google_conversion_id = "<?php echo $this->getConversionId() ?>";`
To:
`    var google_conversion_id = <?php echo $this->getConversionId() ?>;`

Those notices about having the currency look bogus as the google code from AdWords does not seem to include that. 

After fixing the quotations, it complains about a non-standard implementation. Maybe we can update this for the more current google code too?

![screen-shot-2016-04-07-at-5 19 06-am](https://cloud.githubusercontent.com/assets/8039413/14344903/9de245ee-fc80-11e5-9051-da4907246ece.png)

Cheers!
Gus

**Comment by tavinus** [comment]
I have made a pull request with the change.
Cheers!

**Comment by quafzi** [comment]
Thank you!
