### ISSUE TITLE
README.md file and backend location

### ISSUE THREAD

**Issue by tavinus** [quafzi/Inchoo_Adwords#4]
Hi there,

Thanks for maintaining this extension.
It would really be nice to have a readme file with instructions for installing and using.

It is very simple, I know. But some people may get confused like I did, looking for the backend part as it was with the original Inchoo plugin. took me some time to find the options under Sales > Google API.

Installing is not much different from any other extension, but having the info would also be nice. I installed it manually (using curl and cp -av), so not even sure modman works.

I will try to write a readme file but I am not used to github. How would you suggest I try to send any additions or new files? I fork, change and then ask for merge?

Should I just post my README.md suggestion here?

**Comment by quafzi** [comment]
@tavinus Fork + Pull Request would be nice :)

**Comment by tavinus** [comment]
Done then... Another typo fix there and closing this.
